// frontend/src/components/Map/Map.tsx
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";

import "./styles.css";

export const Map = () => {
  return (
    <MapContainer center={[40.181389, 44.514444]} zoom={13} maxZoom={18} scrollWheelZoom={true} className="map">
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <Marker position={[51.505, -0.09]}>
        <Popup>
          A pretty CSS3 popup. <br /> Easily customizable.
        </Popup>
      </Marker>
    </MapContainer>
  );
};

// frontend-v2/src/lib/components/Map.svelte
<script>
	import { onMount } from 'svelte';
	import 'leaflet/dist/leaflet.css';

	export let center = [51.505, -0.09];

	let map;
	let L;

	onMount(async () => {
		L = await import('leaflet');
		map = L.map('map').setView(center, 18);

		L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
			maxZoom: 19
		}).addTo(map);

		map.attributionControl.setPrefix('github.com/umonkey');
	});
</script>

<div id="map"></div>

<style>
	#map {
		height: 400px;
	}
</style>
