// frontend/src/components/maps/Map/Map.tsx
import { MapControl } from "@/components";
import { DEFAULT_MAP_CENTER } from "@/utils/config";

import "./styles.css";

interface IProps {
  onAddTree: () => void;
}

export const Map = (props: IProps) => {
  const handleAddTree = () => {
    console.debug("Showing add tree form...");
    props.onAddTree();
  };

  return (
    <MapControl
      center={DEFAULT_MAP_CENTER}
      onAddTree={handleAddTree}
      picker={false}
    />
  );
};

// frontend-v2/src/routes/map/+page.svelte
<script>
	import Header from '$lib/components/tree/Header.svelte';
	import Map from '$lib/components/Map.svelte';
	import { DEFAULT_MAP_CENTER } from '$lib/constants';

	const onChange = (tree) => {
		console.debug('TREE SELECTED', tree);
	};
</script>

<svelte:head>
	<title>Map</title>
</svelte:head>

<Header />

<Map center={DEFAULT_MAP_CENTER} {onChange} />
